/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jq7SsOrtWMJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import React from 'react';

function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  );
}

export function ScoreCard() {
  const score = 75; // Example score
  const passPercentage = 75;
  const isPass = score >= passPercentage;

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100 relative">
      <h1 className="absolute top-4 left-4 text-3xl font-bold">Score Card</h1>
      <div className="w-full max-w-5xl mx-auto p-4 md:p-12">
        <div className="bg-card rounded-lg shadow-lg p-12 grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="flex flex-col items-center justify-center">
            <div className="text-8xl font-bold mb-4 text-primary">{score}</div>
            <div
              className={`px-4 py-2 rounded-full font-medium ${
                isPass ? 'bg-green-500 text-green-50' : 'bg-red-500 text-red-50'
              }`}
            >
              {isPass ? 'Pass' : 'Fail'}
            </div>
            <div className="mt-2 px-4 py-2 rounded-full bg-gray-200 text-gray-700 font-medium">
              Pass percentage: {passPercentage}%
            </div>
          </div>
          <div className="space-y-6">
            <div className="space-y-2">
              <h2 className="text-2xl font-bold">Summary</h2>
              <p className="text-muted-foreground">
                {isPass
                  ? `Congratulations! You have passed the assessment with a score of ${score}. Keep up the great work!`
                  : `Unfortunately, you did not pass the assessment. Your score is ${score}. Please review the areas for improvement and try again.`}
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-2xl font-bold">Areas for Improvement</h2>
              <ul className="space-y-2">
                <li className="flex items-center gap-2">
                  <ChevronRightIcon className="w-5 h-5 text-muted-foreground" />
                  <span className="text-muted-foreground">Improve time management skills</span>
                </li>
                <li className="flex items-center gap-2">
                  <ChevronRightIcon className="w-5 h-5 text-muted-foreground" />
                  <span className="text-muted-foreground">Focus on attention to detail</span>
                </li>
                <li className="flex items-center gap-2">
                  <ChevronRightIcon className="w-5 h-5 text-muted-foreground" />
                  <span className="text-muted-foreground">Enhance problem-solving skills</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
